# defaults:
#   - ../../base@_here_
#   - _self_

# tttttttttttttt: ${concat:xxx, yyy}

# override
device: 2
test_image: deploy/assets/5.jpg  # test image, when using model.test()  [optional] 
model_class: PlayingPhoneModel   # required
component_name: untitled   # TODO
description: Model for detecting people who's playing_phone!


# modules
modules:  # don't change this name
  - playing_phone:  # model_name, required
      model_type: detector   # required   (detector, classifier, others) 
      model_weights: deploy/projects/playing_phone/weights/play_phone_221202.onnx  # required
      # model_weights: deploy/projects/playing_phone/weights/yolov8n-nms.onnx  # required
      
      input_size: 800   # optional
      conf_threshold: 0.6   # required
      nms_threshold: 0.4   # required
      classes_names:  # optional
        0: cellphone
        1: playing_phone   
      min_bbox_size: 20   # min detection bouding box
      overlap_self_iou: 0.92  # phone and playing_phone iou


  # - another_model_name:
      # model_type: classifier
      # ...
